//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCUI.AdminServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddTrain", ReplyAction="http://tempuri.org/IAdminService/AddTrainResponse")]
        string AddTrain(ServerWCF.Train tr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddTrain", ReplyAction="http://tempuri.org/IAdminService/AddTrainResponse")]
        System.Threading.Tasks.Task<string> AddTrainAsync(ServerWCF.Train tr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddStation", ReplyAction="http://tempuri.org/IAdminService/AddStationResponse")]
        string AddStation(ServerWCF.Station st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddStation", ReplyAction="http://tempuri.org/IAdminService/AddStationResponse")]
        System.Threading.Tasks.Task<string> AddStationAsync(ServerWCF.Station st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddTrack", ReplyAction="http://tempuri.org/IAdminService/AddTrackResponse")]
        string AddTrack(ServerWCF.Track trk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddTrack", ReplyAction="http://tempuri.org/IAdminService/AddTrackResponse")]
        System.Threading.Tasks.Task<string> AddTrackAsync(ServerWCF.Track trk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddStationToTrack", ReplyAction="http://tempuri.org/IAdminService/AddStationToTrackResponse")]
        string AddStationToTrack(ServerWCF.Track trk, ServerWCF.Station st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddStationToTrack", ReplyAction="http://tempuri.org/IAdminService/AddStationToTrackResponse")]
        System.Threading.Tasks.Task<string> AddStationToTrackAsync(ServerWCF.Track trk, ServerWCF.Station st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/LoadStations", ReplyAction="http://tempuri.org/IAdminService/LoadStationsResponse")]
        ServerWCF.Station[] LoadStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/LoadStations", ReplyAction="http://tempuri.org/IAdminService/LoadStationsResponse")]
        System.Threading.Tasks.Task<ServerWCF.Station[]> LoadStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTracks", ReplyAction="http://tempuri.org/IAdminService/GetTracksResponse")]
        ServerWCF.Track[] GetTracks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTracks", ReplyAction="http://tempuri.org/IAdminService/GetTracksResponse")]
        System.Threading.Tasks.Task<ServerWCF.Track[]> GetTracksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : ClientCUI.AdminServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<ClientCUI.AdminServiceReference.IAdminService>, ClientCUI.AdminServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddTrain(ServerWCF.Train tr) {
            return base.Channel.AddTrain(tr);
        }
        
        public System.Threading.Tasks.Task<string> AddTrainAsync(ServerWCF.Train tr) {
            return base.Channel.AddTrainAsync(tr);
        }
        
        public string AddStation(ServerWCF.Station st) {
            return base.Channel.AddStation(st);
        }
        
        public System.Threading.Tasks.Task<string> AddStationAsync(ServerWCF.Station st) {
            return base.Channel.AddStationAsync(st);
        }
        
        public string AddTrack(ServerWCF.Track trk) {
            return base.Channel.AddTrack(trk);
        }
        
        public System.Threading.Tasks.Task<string> AddTrackAsync(ServerWCF.Track trk) {
            return base.Channel.AddTrackAsync(trk);
        }
        
        public string AddStationToTrack(ServerWCF.Track trk, ServerWCF.Station st) {
            return base.Channel.AddStationToTrack(trk, st);
        }
        
        public System.Threading.Tasks.Task<string> AddStationToTrackAsync(ServerWCF.Track trk, ServerWCF.Station st) {
            return base.Channel.AddStationToTrackAsync(trk, st);
        }
        
        public ServerWCF.Station[] LoadStations() {
            return base.Channel.LoadStations();
        }
        
        public System.Threading.Tasks.Task<ServerWCF.Station[]> LoadStationsAsync() {
            return base.Channel.LoadStationsAsync();
        }
        
        public ServerWCF.Track[] GetTracks() {
            return base.Channel.GetTracks();
        }
        
        public System.Threading.Tasks.Task<ServerWCF.Track[]> GetTracksAsync() {
            return base.Channel.GetTracksAsync();
        }
    }
}
