//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.ServiceModel;

namespace ServerWCF
{
    [DataContract]
    public partial class Admin : User
    {
        [DataMember]
        public int AdminId { get; set; }
    }
}
