//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace ServerWCF
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Track
    {
        public Track()
        {
            this.Trains = new HashSet<Train>();
            this.Stations = new HashSet<Station>();
            this.Bookings = new HashSet<Booking>();
        }
    
        [DataMember]
        public int TrackId { get; set; }
        [DataMember]
        public string FromStation { get; set; }
        [DataMember]
        public string ToStation { get; set; }
        [DataMember]
        public string TimeToLeave { get; set; }
        [DataMember]
        public string TimeToArrive { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Price { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Train> Trains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Station> Stations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
