//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace ServerWCF
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Train
    {
        public Train()
        {
            this.Tracks = new HashSet<Track>();
        }

        [DataMember]
        public int TrainId { get; set; }

        [DataMember]
        public string Model { get; set; }

        [DataMember]
        public string Type { get; set; }

        [DataMember]
        public int Capacity { get; set; }
    
        [DataMember]
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
