//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCUI.ServerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerServiceReference.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/LoadStations", ReplyAction="http://tempuri.org/IServerService/LoadStationsResponse")]
        ServerWCF.Station[] LoadStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/LoadStations", ReplyAction="http://tempuri.org/IServerService/LoadStationsResponse")]
        System.Threading.Tasks.Task<ServerWCF.Station[]> LoadStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetTracks", ReplyAction="http://tempuri.org/IServerService/GetTracksResponse")]
        ServerWCF.Track[] GetTracks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetTracks", ReplyAction="http://tempuri.org/IServerService/GetTracksResponse")]
        System.Threading.Tasks.Task<ServerWCF.Track[]> GetTracksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : ClientCUI.ServerServiceReference.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<ClientCUI.ServerServiceReference.IServerService>, ClientCUI.ServerServiceReference.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServerWCF.Station[] LoadStations() {
            return base.Channel.LoadStations();
        }
        
        public System.Threading.Tasks.Task<ServerWCF.Station[]> LoadStationsAsync() {
            return base.Channel.LoadStationsAsync();
        }
        
        public ServerWCF.Track[] GetTracks() {
            return base.Channel.GetTracks();
        }
        
        public System.Threading.Tasks.Task<ServerWCF.Track[]> GetTracksAsync() {
            return base.Channel.GetTracksAsync();
        }
    }
}
